---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGAzCCA+ugAwIBAgIURZy+Z7jWHeR9HTFNGbAnJz4LtgQwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxDzANBgNVBAgMBk1hZHJpZDEVMBMGA1UEBwwMU2Fu
    IEJlcm5hcmRvMRIwEAYDVQQKDAlLYXJtYWxhYnMxDzANBgNVBAsMBkd1aXRhcjEi
    MCAGA1UEAwwZcmVnaXN0cnkuaHlwZXJzaGlmdGJtLmxhYjAeFw0yMzA5MTQxNTA2
    MzBaFw0zMzA5MTExNTA2MzBaMH4xCzAJBgNVBAYTAlVTMQ8wDQYDVQQIDAZNYWRy
    aWQxFTATBgNVBAcMDFNhbiBCZXJuYXJkbzESMBAGA1UECgwJS2FybWFsYWJzMQ8w
    DQYDVQQLDAZHdWl0YXIxIjAgBgNVBAMMGXJlZ2lzdHJ5Lmh5cGVyc2hpZnRibS5s
    YWIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCkh8UMPQW9VKjDLRO5
    yqELUrB9v/2j/UiIKW+d/g2kFWx5tJHZAkIQDkSnUhRP5CkmEyr9CpxUpgoN+Vrb
    +bBi76Wm0ly5ZufAw440B2SL+Jdgo8FumLkjNqFN90vqewMEzKfAqgK2ZhctKBsY
    v+7i9ipzPmYR8J6W2JbjTD9FWJoV41oICOHOHc2brNIoJ5GfVmksQO5r9QFREU/a
    f0p44YkyMxAFZ0mNhU1/5GAxXWw9YTdaYhKzRMuGofzBToXdlP6OE11Z0nMxAyNW
    7wCQs9B9vox+bk276xFtBzKFON9w6nRf8ueNdlepRATRTeLkj2R2idb5MBdORt01
    8RJCt4jG79w6T2HlUDdc59TCThedeAqZmXkRZ7vkrUqN8en6hWF3PVodkUZK3mnR
    F/konvIM1XLq5woghDKyk2655mNKo2ieBsnnPZLWHVf40GiiKxGU1fVzm9nvbzzo
    gjacSBLDUZqRAi6qVfx1w8q74EtUbSWEitQ/ybyj+VDg99AfsUArjZUuuSSFgq5t
    Mhlsvtv1KyLjXvQD3d1V4ebgtPv5+sAWxnZxFG6i1JOruYCHPHYENfYZXVJV8qVx
    qwzcqGNKsRekjAFXsj3oR9GgXoIbX/zDTrzqh5UNvJUMkDZaSOx8m4HniGjaepD3
    XwXkvSs2JWXa2swNySNEAVRQ9wIDAQABo3kwdzAdBgNVHQ4EFgQUFMbnyvJGMo44
    kcHvlPLG9wgJvWQwHwYDVR0jBBgwFoAUFMbnyvJGMo44kcHvlPLG9wgJvWQwDwYD
    VR0TAQH/BAUwAwEB/zAkBgNVHREEHTAbghlyZWdpc3RyeS5oeXBlcnNoaWZ0Ym0u
    bGFiMA0GCSqGSIb3DQEBCwUAA4ICAQChI3571nVpghyVnAyFfai6eppqWTDUIDir
    wJltTWsn595KYrQg9fhjBKXZOWYXgA+smUyr5oUxQRjj8g/EAdak2iT4640Wrvwe
    R8eBsv9oUyAEFu2b85uocMivaKccq9AHAIQRNpK67xXy5CR6+w8UAlfqv+tXhGf8
    abki1mxDW2ZgFltJpU5GZByOnMlHY1sAHBM6X/VIaB5k6+cDpi7ZbWnG/vgzUhzK
    HPRyiwOtWFER2RXF0DU2nSF2CspYTP+A5W94J90t8WZqeP3yh2hww8SQSj0eqaZm
    P0L5UNBTOQXBnmfDmKl7coEWa1oJz53gwBb/20q5cgs2iTJ28yCErJYo31DE7Rx9
    v4WLium2nQEMHAL4098EE4DK57aaH+IpIMtSJBMLKer/yp0jxZzudoMvWm2Vg+qT
    nHNV0nqs+KmjohbDVd1qIoqeuVL707nM0qlMPnXNyLM53YMDD9iwWyZQCZUIvErw
    DfhbTgA+6Rof1OHK5Hl8PbteMiSblnPwrjhVNjPpSThKaaWAStEYpQMtMbSiJsp8
    WauYLuNPrZCNoPNX1Meeh6WwJN+vpVA9JklmOCPMQqbN+NMMMaUq5h5r114FAO+A
    Kr4krXAlaCtsQ5c9KbWYf29I+iuoKxA/zcYgTGyVmoEEZHyfzfnP9oCV0sCpWbet
    LtDbTGdPaw==
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/openshift4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift4"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhacm2"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/rhacm2"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/rhel8"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/rhel8"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/multicluster-engine"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/multicluster-engine"

    [[registry]]
    prefix = ""
    location = "registry.redhat.io/lvms4"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/lvms4"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift/release"

    [[registry]]
    prefix = ""
    location = "quay.io/openshift-release-dev/ocp-release"
    mirror-by-digest-only = true

    [[registry.mirror]]
      location = "registry.hypershiftbm.lab:5000/openshift/release-images"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: multicluster-engine
data:
  PUBLIC_CONTAINER_REGISTRIES: "quay.io,registry.ci.openshift.org,registry.redhat.io"
  ALLOW_CONVERGED_FLOW: "false"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-config
  name: agent
  namespace: multicluster-engine
spec:
  mirrorRegistryRef:
    name: custom-registries
  databaseStorage:
    storageClassName: lvms-vg1
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    storageClassName: lvms-vg1
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: "4.14"
    rootFSUrl: http://registry.hypershiftbm.lab:8080/images/rhcos-414.92.202310170514-0-live-rootfs.x86_64.img
    url: http://registry.hypershiftbm.lab:8080/images/rhcos-414.92.202310170514-0-live.x86_64.iso
    version: 414.92.202310170514-0
  - cpuArchitecture: x86_64
    openshiftVersion: "4.15"
    rootFSUrl: http://registry.hypershiftbm.lab:8080/images/rhcos-415.92.202403270524-0-live-rootfs.x86_64.img
    url: http://registry.hypershiftbm.lab:8080/images/rhcos-415.92.202403270524-0-live.x86_64.iso
    version: 415.92.202403270524-0
  - cpuArchitecture: x86_64
    openshiftVersion: "4.16"
    rootFSUrl: http://registry.hypershiftbm.lab:8080/images/rhcos-416.94.202405291527-0-live-rootfs.x86_64.img
    url: http://registry.hypershiftbm.lab:8080/images/rhcos-416.94.202405291527-0-live.x86_64.iso
    version: 415.92.202403270524-0
