---
- name: BASE - Get the list of services
  service_facts:

- name: BASE - Install SELinux
  dnf:
    name:
      - selinux-policy
      - python3-libselinux
      - python3-libsemanage
    state: present

- name: BASE - Configure sysctl for IPv4 and IPv6
  copy:
    dest: "/etc/sysctl.d/ipv6.conf"
    content: |
      net.ipv4.conf.all.rp_filter=0
      net.ipv6.conf.all.forwarding=1
      net.ipv6.conf.all.accept_ra=2
      net.ipv6.conf.lo.disable_ipv6=0

- name: BASE - Apply system sysctl config
  command: "sysctl --system"

- name: BASE - Disable SELinux in the current session
  seboolean:
    name: selinuxuser_use_ssh_chroot
    state: false
    persistent: true
  register: msg
  tags: 'molecule-notest'
  failed_when: false

- name: BASE - Disable SELinux permanently after reboot
  selinux:
    policy: targeted
    state: disabled

- name: BASE - Stop and disable firewalld service
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no
  tags: 'molecule-notest'
  when: ansible_facts['services']['firewalld.service']['status'] != 'not-found'

- name: BASE - Create forcedns dispatcher script
  template:
    src: forcedns.j2
    dest: /etc/NetworkManager/dispatcher.d/forcedns
    mode: 0755

- name: BASE - Execute the forcedns script
  command: /etc/NetworkManager/dispatcher.d/forcedns
  register: disp
  tags: 'molecule-notest'

- name: BASE - Set the server hostname
  hostname:
    name: "{{ server_fqdn }}"
  tags: 'molecule-notest'

- name: BASE - Create the /root/baremetal/hub/ directory
  file:
    path: /root/baremetal/hub
    state: directory
    mode: '0755'

- name: BASE - Create the /root/baremetal/hub/openshift_pull.json file
  copy:
    content: "{{ pullSecret }}"
    dest: /root/baremetal/hub/openshift_pull.json
