---
- name: DNSMASQ - Create /opt/dnsmasq folder
  file:
    path: /opt/dnsmasq
    state: directory

- name: DNSMASQ - Create dnsmasq.conf file
  template:
    src: templates/dnsmasq.conf.j2
    dest: /opt/dnsmasq/dnsmasq.conf

- name: DNSMASQ - Create hosts.leases file
  file:
    path: /opt/dnsmasq/hosts.leases
    state: touch

- name: DNSMASQ - Create upstream-resolv.conf file
  copy:
    dest:  /opt/dnsmasq/upstream-resolv.conf
    content: |
      ## File generate via Ansible

      nameserver {{ upstream_dns_01 }}
      nameserver {{ upstream_dns_02 }}

- name: DNSMASQ - Create include.d directory
  file:
    path: /opt/dnsmasq/include.d
    state: directory

- name: DNSMASQ - Create dnsmasq-virt systemd unit
  template:
    src: templates/dnsmasq-virt.service.j2
    dest: /etc/systemd/system/dnsmasq-virt.service
  notify:
    - Enable and start dnsmasq-virt service

- name: DNSMASQ - Create infra dual file
  template:
    src: templates/infra.dual.j2
    dest: /opt/dnsmasq/include.d/infra.dual

- name: DNSMASQ - Create hub dual file
  template:
    src: templates/hub.dual.j2
    dest: /opt/dnsmasq/include.d/hub.dual

- name: DNSMASQ - Create hosted dual file
  template:
    src: templates/hosted.dual.j2
    dest: /opt/dnsmasq/include.d/hosted.dual