---
- name: KCLI - Enable COPR karmab/kcli repo
  community.general.copr:
    name: karmab/kcli

- name: KCLI - Install kcli package from the karmab/kcli repo
  dnf:
    name: kcli
    state: present

- name: KCLI - Create kcli pool
  command: kcli create pool -p /var/lib/libvirt/images default
  ignore_errors: yes

- name: KCLI - Create kcli host
  command: kcli create host kvm -H 127.0.0.1 local
  ignore_errors: yes

- name: KCLI - Create kcli network (Default)
  command: kcli create network -c 192.168.122.0/24 default
  ignore_errors: yes

- name: KCLI - Create kcli network (IPv6)
  command: kcli create network -c {{ ipv6_network }}::0/{{ ipv6_mask }} -P dhcp=false -P dns=false --domain {{ server_fqdn }} --nodhcp {{ ipv6_network_name }}
  ignore_errors: yes

- name: KCLI - Create kcli network (IPv4)
  command: kcli create network -c {{ ipv4_network }}.0/{{ ipv4_mask }} -P dhcp=false -P dns=false --domain {{ server_fqdn }} --nodhcp {{ ipv4_network_name }}
  ignore_errors: yes

- name: KCLI - Create kcli network (Dual)
  command: kcli create network -c {{ dual_ipv4_network }}.0/{{ dual_ipv4_mask }} -P dhcp=false -P dns=false -d {{ dual_ipv6_network }}::0/{{ dual_ipv6_mask }} --domain {{ server_fqdn }} --nodhcp {{ dual_network_name }}
  ignore_errors: yes
