---
- name: KCLI - Enable COPR karmab/kcli repo
  community.general.copr:
    name: karmab/kcli

- name: KCLI - Install kcli package from the karmab/kcli repo
  dnf:
    name: kcli
    state: present

- name: KCLI - Create kcli pool
  command: kcli create pool -p /var/lib/libvirt/images default
  ignore_errors: yes

- name: KCLI - Create kcli host
  command: kcli create host kvm -H 127.0.0.1 local
  ignore_errors: yes

- name: KCLI - Create kcli network
  command: kcli create network -c 192.168.122.0/24 default
  ignore_errors: yes
