---
- name: PACKAGES - Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - dnsmasq
    - radvd
    - vim
    - golang
    - podman
    - bind-utils
    - net-tools
    - httpd-tools
    - tree
    - strace
    - tmux
    - wget
    - libvirt
    - libvirt-daemon-driver-qemu
    - qemu-kvm
    - httpd
    - jq
    - skopeo
    - libseccomp-devel
  notify:
    - Enable and start podman service

- name: PACKAGES - Create a new group called libvirt
  group:
    name: libvirt
    state: present

- name: PACKAGES - Add the current user to groups qemu and libvirt
  user:
    name: "{{ ansible_user }}"
    groups: "qemu,libvirt"
    append: yes

- name: PACKAGES - Set ACL for /var/lib/libvirt/images directory
  acl:
    entity: "{{ ansible_user }}"
    etype: user
    permissions: rwx
    path: /var/lib/libvirt/images
    state: present
  notify:
    - Enable and start libvirtd service

- meta: flush_handlers