---
- name: "[packages] Install required packages"
  ansible.builtin.dnf:
    name:
      - dnsmasq
      - radvd
      - vim
      - golang
      - libvirt
      - libvirt-daemon-driver-qemu
      - qemu-kvm
    state: present

- name: "[packages] Start and enable Libvirtd"
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true