---
- name: KSUSHY - Install python3-pyOpenSSL and enable EPEL packages
  dnf:
    name:
      - python3-pyOpenSSL.noarch
      - epel-release
    state: present

- name: KSUSHY - Install python3-cherrypy package
  dnf:
    name:
      - python3-cherrypy
    update_cache: true
    state: present

- name: KSUSHY - Execute kcli create sushy-service command
  command: kcli create sushy-service --ssl --ipv6 --port 9000
  notify:
    - Enable and start ksushy service

- meta: flush_handlers
  tags: 'molecule-notest'

- name: KSUSHY - Restart libvirtd service
  systemd:
    name: libvirtd
    state: restarted
    enabled: yes
  tags: 'molecule-notest'
