---
# Handlers
- name: Enable and start podman service
  systemd:
    name: podman
    state: started
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and start libvirtd service
  systemd:
    name: libvirtd
    state: restarted
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and restart dnsmasq-virt service
  systemd:
    name: dnsmasq-virt
    state: restarted
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and start radvd service
  systemd:
    name: radvd
    state: restarted
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and start ksushy service
  systemd:
    name: ksushy
    state: restarted
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and start registry service
  systemd:
    name: registry
    state: started
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"

- name: Enable and start websrv-ai service
  systemd:
    name: websrv-ai
    state: started
    daemon_reload: true
    enabled: yes
  when:
    - skip_handlers | default("false") == "false"
