apiVersion: v1
data:
  ca-bundle.crt: |
    # Registry server
    -----BEGIN CERTIFICATE-----
    MIIGAzCCA+ugAwIBAgIURZy+Z7jWHeR9HTFNGbAnJz4LtgQwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxDzANBgNVBAgMBk1hZHJpZDEVMBMGA1UEBwwMU2Fu
    IEJlcm5hcmRvMRIwEAYDVQQKDAlLYXJtYWxhYnMxDzANBgNVBAsMBkd1aXRhcjEi
    MCAGA1UEAwwZcmVnaXN0cnkuaHlwZXJzaGlmdGJtLmxhYjAeFw0yMzA5MTQxNTA2
    MzBaFw0zMzA5MTExNTA2MzBaMH4xCzAJBgNVBAYTAlVTMQ8wDQYDVQQIDAZNYWRy
    aWQxFTATBgNVBAcMDFNhbiBCZXJuYXJkbzESMBAGA1UECgwJS2FybWFsYWJzMQ8w
    DQYDVQQLDAZHdWl0YXIxIjAgBgNVBAMMGXJlZ2lzdHJ5Lmh5cGVyc2hpZnRibS5s
    YWIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCkh8UMPQW9VKjDLRO5
    yqELUrB9v/2j/UiIKW+d/g2kFWx5tJHZAkIQDkSnUhRP5CkmEyr9CpxUpgoN+Vrb
    +bBi76Wm0ly5ZufAw440B2SL+Jdgo8FumLkjNqFN90vqewMEzKfAqgK2ZhctKBsY
    v+7i9ipzPmYR8J6W2JbjTD9FWJoV41oICOHOHc2brNIoJ5GfVmksQO5r9QFREU/a
    f0p44YkyMxAFZ0mNhU1/5GAxXWw9YTdaYhKzRMuGofzBToXdlP6OE11Z0nMxAyNW
    7wCQs9B9vox+bk276xFtBzKFON9w6nRf8ueNdlepRATRTeLkj2R2idb5MBdORt01
    8RJCt4jG79w6T2HlUDdc59TCThedeAqZmXkRZ7vkrUqN8en6hWF3PVodkUZK3mnR
    F/konvIM1XLq5woghDKyk2655mNKo2ieBsnnPZLWHVf40GiiKxGU1fVzm9nvbzzo
    gjacSBLDUZqRAi6qVfx1w8q74EtUbSWEitQ/ybyj+VDg99AfsUArjZUuuSSFgq5t
    Mhlsvtv1KyLjXvQD3d1V4ebgtPv5+sAWxnZxFG6i1JOruYCHPHYENfYZXVJV8qVx
    qwzcqGNKsRekjAFXsj3oR9GgXoIbX/zDTrzqh5UNvJUMkDZaSOx8m4HniGjaepD3
    XwXkvSs2JWXa2swNySNEAVRQ9wIDAQABo3kwdzAdBgNVHQ4EFgQUFMbnyvJGMo44
    kcHvlPLG9wgJvWQwHwYDVR0jBBgwFoAUFMbnyvJGMo44kcHvlPLG9wgJvWQwDwYD
    VR0TAQH/BAUwAwEB/zAkBgNVHREEHTAbghlyZWdpc3RyeS5oeXBlcnNoaWZ0Ym0u
    bGFiMA0GCSqGSIb3DQEBCwUAA4ICAQChI3571nVpghyVnAyFfai6eppqWTDUIDir
    wJltTWsn595KYrQg9fhjBKXZOWYXgA+smUyr5oUxQRjj8g/EAdak2iT4640Wrvwe
    R8eBsv9oUyAEFu2b85uocMivaKccq9AHAIQRNpK67xXy5CR6+w8UAlfqv+tXhGf8
    abki1mxDW2ZgFltJpU5GZByOnMlHY1sAHBM6X/VIaB5k6+cDpi7ZbWnG/vgzUhzK
    HPRyiwOtWFER2RXF0DU2nSF2CspYTP+A5W94J90t8WZqeP3yh2hww8SQSj0eqaZm
    P0L5UNBTOQXBnmfDmKl7coEWa1oJz53gwBb/20q5cgs2iTJ28yCErJYo31DE7Rx9
    v4WLium2nQEMHAL4098EE4DK57aaH+IpIMtSJBMLKer/yp0jxZzudoMvWm2Vg+qT
    nHNV0nqs+KmjohbDVd1qIoqeuVL707nM0qlMPnXNyLM53YMDD9iwWyZQCZUIvErw
    DfhbTgA+6Rof1OHK5Hl8PbteMiSblnPwrjhVNjPpSThKaaWAStEYpQMtMbSiJsp8
    WauYLuNPrZCNoPNX1Meeh6WwJN+vpVA9JklmOCPMQqbN+NMMMaUq5h5r114FAO+A
    Kr4krXAlaCtsQ5c9KbWYf29I+iuoKxA/zcYgTGyVmoEEZHyfzfnP9oCV0sCpWbet
    LtDbTGdPaw==
    -----END CERTIFICATE-----

    # Squid Proxy 
    -----BEGIN CERTIFICATE-----
    MIIDsTCCApmgAwIBAgIJAOMGZ4wPlFDRMA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV
    BAYTAkVTMQ4wDAYDVQQIDAVTcGFpbjEPMA0GA1UEBwwGTWFkcmlkMQ8wDQYDVQQK
    DAZSZWRIYXQxEzARBgNVBAsMCkh5cGVyc2hpZnQxGTAXBgNVBAMMEGh5cGVyc2hp
    ZnRibS5sYWIwHhcNMjQwNjEyMTIwMzQyWhcNMzQwNjEwMTIwMzQyWjBvMQswCQYD
    VQQGEwJFUzEOMAwGA1UECAwFU3BhaW4xDzANBgNVBAcMBk1hZHJpZDEPMA0GA1UE
    CgwGUmVkSGF0MRMwEQYDVQQLDApIeXBlcnNoaWZ0MRkwFwYDVQQDDBBoeXBlcnNo
    aWZ0Ym0ubGFiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoy9f6Lqz
    /UHzeOUUQcPbhAUs8hEQX1H/iX+MkHjCfRnlGLB/k1arDYb+/wjaLV6KlezVPBVY
    LUCZSB2txaJbDnm3Z6GhPZYhUhyRuqLinqvL2CDEreaDtu+Eq5zMgSnjWRdSY1Vj
    Z/4bKAyLIuH31S24Urf+5nr0rIs+uRFCV8yur8lT7H2GM8m615Y+5/OXY61htvSL
    XnPXSgMYScbOCdbw210xPqFHVQicyYirL9GknQ3upUR37IkroybyAxlljZ5sSwIA
    ieJ+my8105d9/pP7B1zG9HLFieVEgP7rLDbNS8dzGkbPtvCeg0dJ/zAPidd85IO7
    uVSchREujlntTQIDAQABo1AwTjAdBgNVHQ4EFgQUQym0vR0TeMbBtZe6Wx4jLJoz
    0k4wHwYDVR0jBBgwFoAUQym0vR0TeMbBtZe6Wx4jLJoz0k4wDAYDVR0TBAUwAwEB
    /zANBgkqhkiG9w0BAQsFAAOCAQEAWl1LhxhMrMldd5xcWekJDO1tghTDRT9UaWAI
    1qWoN719UnUe8G7TvAOo48yGSa6RQyn3rhPvB27VD9jAUwnJ3PyBiTzE2PEjwfEh
    vTUdUA59e+RQJFfcT8Qv8fJaq3hRJ0CHfW3HpOoGzujiHDZ4oyEB05s0CQwBKs7a
    v/g2t1cxnFoNPs0j/JgffN15BEzy3RfY9Rc6eHHWa2y4r6bY7GeCzulkJkn8UyxU
    h/lRTIBOY3Ywmc6pZkCBW8Lpu6nBVxPZOBPmMwMM0fWOskcQyTV006zZekNa9d1z
    DXpzpmsnmQkqEWvugU/ZFpyK8/5nXG8SfV1RLzejYmSHexmcyw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config

