---
galaxy_info:
  author: Juan Manuel Parrilla Madrid
  namespace: hap
  description: Hypervisor Ansible Provisioner
  company: Red Hat, inc
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1
  platforms:
  - name: Centos
    versions:
    - 8
  galaxy_tags: ["openshift", "baremetal", "kcli"]
dependencies: []
